version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'kerberos'
      MYSQL_USER: 'kerberos'
      MYSQL_PASSWORD: 'kerberos'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  kerberos:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    ports:
      # Administration port
      - '8971:8971'
      # Proxy port
      - '8970:8970'
    depends_on:
      - database
    environment:
      KERBEROS_DATABASE_DBNAME: kerberos
      KERBEROS_DATABASE_HOST: database
      KERBEROS_DATABASE_PORT: 3306
      KERBEROS_DATABASE_USER: kerberos
      KERBEROS_DATABASE_PASS: kerberos
      KERBEROS_HTTP_PROXY_HOST: 0.0.0.0
      KERBEROS_HTTP_PROXY_PORT: 8970
      KERBEROS_HTTP_ADMINISTRATION_HOST: 0.0.0.0
      KERBEROS_HTTP_ADMINISTRATION_PORT: 8971
      KERBEROS_MISC_PASSWORD_HASH_COST: 14
