version: '3.7'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'cerberus'
      MYSQL_USER: 'cerberus'
      MYSQL_PASSWORD: 'cerberus'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  redis:
    image: redis:5.0
    restart: always
    ports:
      - '6379:6379'

  cerberus:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    ports:
      # Administration port
      - '8971:8971'
      # Proxy port
      - '8970:8970'
    depends_on:
      - database
    environment:
      CERBERUS_DATABASE_DBNAME: "cerberus"
      CERBERUS_DATABASE_HOST: "database"
      CERBERUS_DATABASE_PORT: 3306
      CERBERUS_DATABASE_USER: "cerberus"
      CERBERUS_DATABASE_PASS: "cerberus"
      CERBERUS_HTTP_PROXY_HOST: "0.0.0.0"
      CERBERUS_HTTP_PROXY_PORT: 8970
      CERBERUS_HTTP_PROXY_ENABLE_KEEP_ALIVE: "true"
      CERBERUS_HTTP_PROXY_KEEP_ALIVE_PERIOD: 5
      CERBERUS_HTTP_PROXY_READ_TIMEOUT: 5
      CERBERUS_HTTP_ADMINISTRATION_HOST: "0.0.0.0"
      CERBERUS_HTTP_ADMINISTRATION_PORT: 8971
      CERBERUS_LEADER_CACHE_REFRESH_TIME: 10
      CERBERUS_LEADER_LOCK_REFRESH_TIME: 10
      CERBERUS_MISC_PASSWORD_HASH_COST: 14
      CERBERUS_MISC_SERVICE_HOT_MEMORY_TTL: 30
      CERBERUS_REDIS_DBID: 0
      CERBERUS_REDIS_HOST: "redis"
      CERBERUS_REDIS_PASS: ""
      CERBERUS_REDIS_PORT: 6379
      CERBERUS_REDIS_SERVICE_TTL: 120
