
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "07:00"
    commit-message:
      prefix: "Upgrade:"
    labels:
      - go
      - chore
      - dependencies
