version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - QRaimbault
    assignees:
      - QRaimbault
    labels:
      - chore
      - go
      - dependencies
    ignore:
      - dependency-name: github.com/valyala/fasthttp
        versions:
          - 1.18.0
          - 1.19.0
      - dependency-name: github.com/fasthttp/router
        versions:
          - 1.3.4
          - 1.3.5
