before:
  hooks:
    - go mod download

builds:
  - binary: cerberus
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
