// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7ac1018e048dd32ee118f59b9f1f90cc"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"ce02b9e84e59cf013798fd8457e3bc32": "1f8b08000000000000ff9c93496fdb301085effa1573a3843a40dc052d60f8c048d344a84ca93479c8c9622dd626502d20e9a43fbf90e2465e0a15c845438cde1b90ef236f6ee05d6d7656790db20b628e5420087a9721944edb27b3d52584014069aa124ce3c3f93c8243e3ccaed115b05c00935906548a7c93b298e30a9998f58646d5ba842765b77b65c3f987db689427f895ca4c002183b4d26e6b4de74ddb94e0f56fffaa1c7e77caefc7495383bcb23bed3707fb6bd4bfff3461a8b5dfb7952bc1691f927b1464468a7c3d14d97f1f9026644612cc50209911c169dcd7bc1069ced6243adb6ac1d315e58ff00d1f21ec238bfaae64e9778943f3984af852a3200264f729c365da346d72f7babdf881f2358ae5c1fffc52fff8b8082ed81c9cb66f05d37bcfe14c25d429e79e5b5b9da0bc9d90eb5a9993f0e753a3b7562bafab8df22554ca6b6f6a7d2d8e25e7c8c446a42b5c0bba2a5e0ed155d7debf96c19f339045d267f6cf09ff4735e6148eeb2bd5f1c0e171718df49cc0f2f304e3d3e798b4cf4d90f0bcb87c8e8bb3ee7011167f020000ffffbbc7e77fc8030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "../migrations")
		b.SetResolver("1_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "ce02b9e84e59cf013798fd8457e3bc32"})
	}()

	return nil
}()
