// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "12f56a8e9cad1d70c48d5381e2e41749"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d0ab4e31a2ec17dcbc5acaf26540c060": "1f8b08000000000000ff9c94cf8e9b3010c6ef3cc5dc0c2a2b6db68d5429da030bd35d54622831873d811bdcc452f923dbd9ede3579028404853692f18797e33f67cdfc87777f0a9923bc58d80acb5fc143d86c0bca708a1d042bdc9ad28c0b6000a5916206b632f160e1c6a2d77b52881c60c681645e0652cce43eaa7b846cadc2ea1e69528e08dabed9e2b7bf1f9de39e37dbc147aab646b64531760c41f330d9f4ecf5b6ef643995915c3d54e987cdf6833500fcb4bac1266df94ba002d8c4d9e91119724f1a65fb2eefb825e405c1260840c894b58eaf9dd1a272c8ce9865c3fb66d94b9224b80dfbc2cba824f7a79582e9d199aa4e1da4b5fe13bbe82dd89ee74bb190d7f64d86f9e74b58feb2c3a962d3f76ddc11335dd410fc77200e97348f131aceb267882f38dfc172fdd207b3c985f5fab9f5f56d6c5781cb4501f9d8d2e773a1f63c7ce5720a4a75baef57ba3cad134dddfc045c5e5ef117babf456096e4499735340c98d30b21273d8cfd21429cb59b8c60df3d6c9b189b69ce78efd84984296049d66572bfcdfeb41277bf89f51a786edd3cfdcd37f5b3a7e0082e6bdb682344e2e1f80d564b7f77df5370000ffffd3a6fe7e3a040000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "../migrations")
		b.SetResolver("1_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "d0ab4e31a2ec17dcbc5acaf26540c060"})
	}()

	return nil
}()
